config:
  absolute_path: /home/guga/experiments/Thesis
  repeat: 1
  copy_logs: true
  logs_dir: testing/logs/
  docker_dir: testing/docker/
  data_dir: testing/data/
  configuration_dir: testing/configuration/
  top_website_path: testing/resources/websites.txt
  clients: 9000

combinations:
  tcpdump: false
  #filesize: ["51200", "1048576", "5242880"]
  filesize: ["5242880"]
  end_test_at: 120
  clients:
    # [Bulk Clients, Web Clients, Top Web Clients]
    - [0, 5, 0]

  tor:
    dummy: [0, 0.01, 0.1]
    max_jitter: [10]
    min_jitter: [1]
    target_jitter: [2]
    dp_distribution: ["LAPLACE"]
    dp_epsilon: [0.0]
    scheduler: ["PRIV_KIST"] # "PRIV_Vanilla"
