services:
  authority:
    image: dptor_node
    command: ["authority"]
    volumes:
      - ./configuration/:/app/source/
      - ./logs:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.5
    # healthcheck:
    #   test: "grep 'Published' /app/logs/tor/authority.tor.log || exit 1"
    #   interval: 2s
    #   retries: 30
    #   start_period: 60s

  relay1:
    image: dptor_node  
    command: ["relay1"]  
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.2
    # depends_on:
    #   authority:
    #     condition: service_healthy
    
  relay2:
    image: dptor_node  
    command: ["relay2"]  
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.3
    # depends_on:
    #   authority:
    #     condition: service_healthy

  exit1:
    image: dptor_node
    command: ["exit1"]
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.4
    # depends_on:
    #   authority:
    #     condition: service_healthy  

  client:
    image: dptor_node
    command: ["client"]
    ports:
      - 9000:9000
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.6
    # depends_on:
    #   authority:
    #     condition: service_healthy

  hs:
    image: dptor_node
    command: ["hidden_service"]
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
      - ./configuration/hidden_service/crypto/:/app/hidden_service
    networks:
      net:
        ipv4_address: 10.5.0.20
    # depends_on:
    #   authority:
    #     condition: service_healthy

networks:
  net:
    external: true
      