services:
  authority:
    image: gugarodri/dptor_node:latest
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs:/app/logs/
    environment:
      - NAME=authority
      - RELAY_TYPE=authority
    networks:
      net:
        ipv4_address: 10.5.0.255

  relay1:
    image: gugarodri/dptor_node:latest
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs/:/app/logs/
    environment:
      - NAME=relay1
      - RELAY_TYPE=relay
    networks:
      net:
        ipv4_address: 10.5.0.2
    
  relay2:
    image: gugarodri/dptor_node:latest
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs/:/app/logs/
    environment:
      - NAME=relay2
      - RELAY_TYPE=relay
    networks:
      net:
        ipv4_address: 10.5.0.3

  exit1:
    image: gugarodri/dptor_node:latest
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs/:/app/logs/
    environment:
      - NAME=exit1
      - RELAY_TYPE=exit
    networks:
      net:
        ipv4_address: 10.5.0.4  

  client:
    image: gugarodri/dptor_node:latest
    ports:
      - 9000:9000
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs/:/app/logs/
    environment:
      - NAME=client1
      - RELAY_TYPE=client
    networks:
      net:
        ipv4_address: 10.5.0.6

  httpserver:
    build:
      context: .
      dockerfile: ./testing/docker/httpserver.Dockerfile
    ports:
      - 8000:5000
    networks:
      net:
        ipv4_address: 10.5.0.200

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
      