services:
  authority:
    image: dptor_node
    command: ["authority"]
    volumes:
      - ./configuration/:/app/source/
      - ./configuration/.config:/conf/
      - ./logs:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.255

  relay1:
    image: dptor_node  
    command: ["relay1"]  
    volumes:
      - ./configuration/:/app/source/
      - ./configuration/.config:/conf/
      - ./logs/:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.2
    
  relay2:
    image: dptor_node  
    command: ["relay2"]  
    volumes:
      - ./configuration/:/app/source/
      - ./configuration/.config:/conf/
      - ./logs/:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.3

  exit1:
    image: dptor_node
    command: ["exit1"]
    volumes:
      - ./configuration/:/app/source/
      - ./configuration/.config:/conf/
      - ./logs/:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.4  

  client:
    image: dptor_node
    command: ["client"]
    ports:
      - 9000:9000
    volumes:
      - ./configuration/:/app/source/
      - ./configuration/.config:/conf/
      - ./logs/:/app/logs/
    networks:
      net:
        ipv4_address: 10.5.0.6

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8000:80
    networks:
      net:
        ipv4_address: 10.5.0.200

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
      