services:
  authority:
    image: dptor_node
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs:/app/logs/
    environment:
      - NAME=authority
      - RELAY_TYPE=authority
    networks:
      net:
        ipv4_address: 10.5.0.255

  relay1:
    image: dptor_node
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs/:/app/logs/
    environment:
      - NAME=relay1
      - RELAY_TYPE=relay1
    networks:
      net:
        ipv4_address: 10.5.0.2
    
  relay2:
    image: dptor_node
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs/:/app/logs/
    environment:
      - NAME=relay2
      - RELAY_TYPE=relay2
    networks:
      net:
        ipv4_address: 10.5.0.3

  exit1:
    image: dptor_node
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs/:/app/logs/
    environment:
      - NAME=exit1
      - RELAY_TYPE=exit1
    networks:
      net:
        ipv4_address: 10.5.0.4  

  client:
    image: dptor_node
    ports:
      - 9000:9000
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs/:/app/logs/
    environment:
      - NAME=client1
      - RELAY_TYPE=client
    networks:
      net:
        ipv4_address: 10.5.0.6

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8000:80
    networks:
      net:
        ipv4_address: 10.5.0.200

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
      