services:
  authority:
    image: dptor_node
    command: ["authority"]
    volumes:
      - ./configuration/:/app/source/
      - ./logs:/app/logs/
      - ./test/extract/:/app/extract/
    networks:
      net:
        ipv4_address: 10.5.0.5

  relay1:
    image: dptor_node  
    command: ["relay1"]  
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
      - ./test/extract/:/app/extract/
    networks:
      net:
        ipv4_address: 10.5.0.2
    
  relay2:
    image: dptor_node  
    command: ["relay2"]  
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
      - ./test/extract/:/app/extract/
    networks:
      net:
        ipv4_address: 10.5.0.3

  exit1:
    image: dptor_node
    command: ["exit1"]
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
      - ./test/extract/:/app/extract/
    networks:
      net:
        ipv4_address: 10.5.0.4  

  client:
    image: dptor_node
    command: ["client"]
    ports:
      - 9000:9000
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
      - ./test/extract/:/app/extract/
    networks:
      net:
        ipv4_address: 10.5.0.6

  hs:
    image: dptor_node
    command: ["hidden_service"]
    volumes:
      - ./configuration/:/app/source/
      - ./logs/:/app/logs/
      - ./configuration/hidden_service/crypto/:/app/hidden_service
      - ./test/extract/:/app/extract/
    networks:
      net:
        ipv4_address: 10.5.0.20

networks:
  net:
    external: true
      