#!/bin/bash

case "$1" in
"r" | "run")
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/jitter.yaml -v"
    exit 0
    ;;
"dummy")
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/configs/dummy.perf.yaml -v"
    exit 0
    ;;
"jitter")
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/configs/jitter.perf.yaml -v"
    exit 0
    ;;
"jd")
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/configs/jitterdummy.perf.yaml -v"
    exit 0
    ;;


"t1")
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/control.perf.yaml -v | tee testing/scripts/tester/control.perf.log"
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/dummy.perf.yaml -v | tee testing/scripts/tester/dummy.perf.log"
    exit 0
    ;;
"b" | "build")
    docker buildx build \
        -t gugarodri/dptor_base \
        -f testing/docker/base.Dockerfile \
        .
    docker buildx build \
        -t gugarodri/dptor_node \
        -f testing/docker/node.Dockerfile \
        .
    docker buildx build \
        -t gugarodri/dptor_swarm \
        -f testing/docker/swarm.Dockerfile \
        .
    exit 0
    ;;
"push")
    docker push gugarodri/dptor_base
    docker push gugarodri/dptor_node
    docker push gugarodri/dptor_swarm
    exit 0
    ;;
"s" | "swarm")
    sh -c "./testing/scripts/tester/swarm.sh -c testing/scripts/tester/config.yaml -v"
    exit 0
    ;;
"a" | "analyze")
    python3 -m venv testing/scripts/analyzer/venv
    source testing/scripts/analyzer/venv/bin/activate
    pip install -r testing/scripts/analyzer/requirements.txt
    sh -c "python3 testing/scripts/analyzer/main.py"
    deactivate
    exit 0
    ;;
"p" | "plot")
    python3 -m venv testing/scripts/ploter/venv
    source testing/scripts/ploter/venv/bin/activate
    pip install -r testing/scripts/ploter/requirements.txt
    sh -c "python3 testing/scripts/ploter/main.py"
    deactivate
    exit 0
    ;;
"c" | "config")
    nano testing/scripts/tester/config.yaml
    exit 0
    ;;
*)
    echo "Invalid option: $1"
    exit 1
    ;;

esac
