#!/bin/bash

case "$1" in
"r" | "run")
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/config.yaml -v"
    exit 0
    ;;

"t1")
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/dummy.yaml -v > testing/scripts/tester/dummy.log"
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/jitter.yaml -v > testing/scripts/tester/jitter.log"
    sh -c "./testing/scripts/tester/monitor.sh -c testing/scripts/tester/config.yaml -v > testing/scripts/tester/config.log"
    exit 0
    ;;
"b" | "build")
    docker buildx build \
        -t gugarodri/dptor_node:latest \
        -f testing/docker/node.Dockerfile \
        .
    docker push gugarodri/dptor_node:latest
    exit 0
    ;;
"a" | "analyze")
    python3 -m venv testing/scripts/analyzer/venv
    source testing/scripts/analyzer/venv/bin/activate
    pip install -r testing/scripts/analyzer/requirements.txt
    sh -c "python3 testing/scripts/analyzer/main.py"
    deactivate
    exit 0
    ;;
"p" | "plot")
    python3 -m venv testing/scripts/ploter/venv
    source testing/scripts/ploter/venv/bin/activate
    pip install -r testing/scripts/ploter/requirements.txt
    sh -c "python3 testing/scripts/ploter/main.py"
    deactivate
    exit 0
    ;;
"c" | "config")
    nano testing/scripts/tester/config.yaml
    exit 0
    ;;
"s" | "swarm")
    sh -c "./testing/scripts/tester/swarm.sh"
    exit 0
    ;;
*)
    echo "Invalid option: $1"
    exit 1
    ;;

esac
