services: 
  authority:
    image: gugarodri/dptor_swarm:latest
    volumes:
      - ./testing/logs:/app/logs/
    environment:
      - RELAY_TYPE=authority
    hostname: "authority"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node == authority
    networks:
      - swarm

  relay-1:
    image: gugarodri/dptor_swarm:latest
    volumes:
      - ./testing/logs/:/app/logs/
    environment:
      - RELAY_TYPE=relay
    hostname: "relay-1"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node == relay1
    networks:
      - swarm

  relay-2:
    image: gugarodri/dptor_swarm:latest
    volumes:
      - ./testing/logs/:/app/logs/
    environment:
      - RELAY_TYPE=relay
    hostname: "relay-2"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node == relay2
    networks:
      - swarm

  exit:
    image: gugarodri/dptor_swarm:latest
    volumes:
      - ./testing/logs/:/app/logs/
    environment:
      - RELAY_TYPE=exit
    hostname: "exit-1"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node == exit1
    networks:
      - swarm
  
  client:
    image: gugarodri/dptor_swarm:latest
    volumes:
      - ./testing/logs/:/app/logs/
    environment:
      - RELAY_TYPE=client
    hostname: "client"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node == client
    networks:
      - swarm
    ports:
      - "9000:9000"

  httpserver:
    image: gugarodri/dptor_httpserver:latest
    networks:
      - swarm
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.node == client


networks:
  swarm:
    driver: overlay
    attachable: true
