services: 
  authority:
      image: gugarodri/dptor_node:latest
      volumes:
        - ./testing/configuration/:/app/conf/
        - ./testing/logs:/app/logs/
      environment:
        - RELAY_TYPE=authority
      hostname: "authority"
      deploy:
        replicas: 1
      networks:
        - swarm

  relay:
      image: gugarodri/dptor_node:latest
      volumes:
        - ./testing/configuration/:/app/conf/
        - ./testing/logs/:/app/logs/
      environment:
        - RELAY_TYPE=relay
      hostname: "relay-{{.Task.Slot}}"
      deploy:
        replicas: 5
      networks:
        - swarm
      depends_on:
      - authority

  exit:
      image: gugarodri/dptor_node:latest
      volumes:
        - ./testing/configuration/:/app/conf/
        - ./testing/logs/:/app/logs/
      environment:
        - RELAY_TYPE=exit
      hostname: "exit-{{.Task.Slot}}"
      deploy:
        replicas: 3
      networks:
        - swarm
      depends_on:
      - authority
  
  client:
    image: gugarodri/dptor_node:latest
    volumes:
      - ./testing/configuration/:/app/conf/
      - ./testing/logs/:/app/logs/
    environment:
      - RELAY_TYPE=client
    hostname: "client-{{.Task.Slot}}"
    deploy:
      replicas: 1
    networks:
      - swarm
    depends_on:
    - authority
    ports:
      - "9000:9000"

networks:
  swarm:
    driver: overlay
