services: 
  authority:
      image: gugarodri/dptor_node:latest
      volumes:
        - ./testing/configuration/:/app/conf/
        - ./testing/logs:/app/logs/
      environment:
        - RELAY_TYPE=authority
      hostname: "authority"
      deploy:
        replicas: 1

  relay:
      image: gugarodri/dptor_node:latest
      volumes:
        - ./testing/configuration/:/app/conf/
        - ./testing/logs/:/app/logs/
      environment:
        - RELAY_TYPE=relay
      hostname: "relay-{{.Task.Slot}}"
      deploy:
        replicas: 2
      networks:
        - swarm

  exit:
      image: gugarodri/dptor_node:latest
      volumes:
        - ./testing/configuration/:/app/conf/
        - ./testing/logs/:/app/logs/
      environment:
        - RELAY_TYPE=exit
      hostname: "exit-{{.Task.Slot}}"
      deploy:
        replicas: 1
      networks:
        - swarm

networks:
  swarm:
    driver: overlay
