config:
  absolute_path: /home/ubuntu/thesis
  repeat: 1
  copy_logs: true
  logs_dir: testing/logs/
  docker_dir: testing/docker/
  data_dir: testing/data/
  configuration_dir: testing/configuration/
  top_website_path: testing/resources/websites.txt
  clients: 9000
  end_test_at: 100
  local: false

combinations:
  filesize: ["1"]
  clients:
    - [0, 0, 1]
  tor:
    dummy: [0, 0.1, 0.25, 0.5, 1, 2.5, 5]
    max_jitter: [10]
    min_jitter: [1]
    target_jitter: [2]
    dp_distribution: ["LAPLACE", "POISSON", "EXPONENTIAL"]
    dp_epsilon: [0, 0.1, 0.25, 0.5, 1, 2.5, 5]

    scheduler: ["PRIV_KIST", "PRIV_Vanilla"]
