config:
  absolute_path: /home/ubuntu/thesis
  repeat: 1
  copy_logs: true
  logs_dir: testing/logs/
  docker_dir: testing/docker/
  data_dir: testing/data/
  configuration_dir: testing/configuration/
  top_website_path: testing/resources/websites.txt
  clients: 9000
  end_test_at: 100

combinations:
  filesize: ["1"]
  clients:
    - [0, 0, 1]
  tor:
    dummy: [-1]
    max_jitter: [10]
    min_jitter: [1]
    target_jitter: [2]
    dp_distribution: ["LAPLACE", "POISSON", "EXPONENTIAL"]
    dp_epsilon: [0, 0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.7, 0.9, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]

    scheduler: ["PRIV_KIST", "PRIV_Vanilla"]
